site_name: Find the Brids wiki
nav:
  - Home: index.md
  - Game Overview: "Game Overview.md"
  - All Brids: "brids/index.md"
   # - 404 Brid: "404 Brid.md"
   # - 8-Brid: "8-Brid.md"
   # - Bee Brid: "Bee Brid.md"
   # - Blue Brid: "Blue Brid.md"
   # - Brid in a Floatie: "Brid in a Floatie.md"
   # - Brid: Brid.md
   # - Bridtain: "Bridtain.md"
   # - Burrowing Brid: "Burrowing Brid.md"
   # - Candy Cane: "Candy Cane Brid.md"
   # - Ceiling Fan: "Ceiling Fan Brid.md"
   # - Choco Brid: "Choco Brid.md"
   # - Farmer Brid: "Farmer Brid.md"
   # - Frosty Brid: "Frosty Brid.md"
   # - Glitch Brid: "Glitch Brid.md"
   # - Green Brid: "Green Brid.md"
   # - Helpless Brid: "Helpless Brid.md"
   # - Lithuanian Brid: "Lithuanian Brid.md"
   # - Lottery Brid: "Lottery Brid.md"
   # - Omnimagical Brid: "Omnimagical Brid.md"
   # - Pizza Brid: "Pizza Brid.md"
   # - R6 Brid: "R6 Brid.md"
   # - Secret Brid: "Secret Brid.md"
   # - Tree Brid: "Tree Brid.md"
   # - Upside-Down Brid: "Upside-Down Brid.md"
   # - Wavy Brid: "Wavy Brid.md"
theme: darkly
