site_name: Find the Brids wiki
nav:
  - Home: index.md
  - Game Overview: "Game Overview.md"
  - All Brids: "brids/index.md"
not_in_nav: |
brids/** # Exclude entire brids dir from showing up as "not in nav"
THEDEPTHSOFTHEEARTH.md
theme: darkly
exclude_docs: |
brids/partialbrid
